# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll Website Test'
description:      'An attempt at creating a Jekyll Site.'
url:              http://spacecadet1016.github.io
baseurl:          /jekyll-workshop-test-site/

author:
  name:           'Shane Willson'
  url:            https://twitter.com/idontusetwitter

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/spacecadet1016/jekyll-workshop-test-site
